#!/bin/bash

P=$(mktemp -u) 
:>$P

fzf-tldr '' $P  

buffer="$(<$P perl -pe 's/\s+$//')"
rm $P

destination_pane="$(</tmp/tmux_fzf-tldr_destination_pane)" 
[[ "$buffer" ]] && sleep .1 ; tmux send-keys -t $destination_pane "$buffer"
